name: Sync branches

on:
  pull_request:
    types:
      - closed
      
      
jobs:
  if_merged:
     # Only run the job if the pull request was merged and merged into the `main` branch
    if: github.event.pull_request.merged == true 
    # && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # actions/checkout@v3

      - name: Open PR to main-emea
        run: |
          gh pr create -B main-emea -H main -t "Sync from main->main-emea from PR #${{ github.event.pull_request.number }}" -b "sync PR" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open PR to main-apac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B main-apac -H main -t "Sync from main->main-apac from PR #${{ github.event.pull_request.number }}" -b "sync PR"

      - name: Open PR to main-na
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B main-na -H main -t "Sync from main->main-na from PR #${{ github.event.pull_request.number }}" -b "sync PR"
